# Generated by Django 3.1.7 on 2021-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0002_auto_20210226_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.TextField(null=True),
        ),
    ]
